# NumPy basic array operations

In [1]:
import numpy as np

In [2]:
a = np.array([5, 6, 9])

In [7]:
a[1]

6

In [8]:
a.ndim

1

In [40]:
b = np.array([[1,2],[3,4],[5,6]])
b.ndim

2

In [9]:
a.itemsize

4

In [10]:
b.itemsize

4

In [11]:
a.dtype

dtype('int32')

In [12]:
b.dtype

dtype('int32')

In [41]:
b = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
b.itemsize

8

In [42]:
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [16]:
a

array([5, 6, 9])

In [17]:
a.size

3

In [18]:
b.size

6

In [19]:
b.shape

(3, 2)

In [43]:
# b = np.array([[1,2],[3,4],[5,6]], dtype=complex)
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((6,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
l=range(5)
l

range(0, 5)

In [28]:
l[1]

1

In [29]:
np.arange(1,5)

array([1, 2, 3, 4])

In [31]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [34]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [35]:
np.linspace(1,5,6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [44]:
b.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [45]:
b.reshape(6,1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [46]:
b.ravel()

array([1., 2., 3., 4., 5., 6.])

In [47]:
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [50]:
b.min()

1.0

In [49]:
b.max()

6.0

In [51]:
a

array([5, 6, 9])

In [53]:
a.sum()

20

In [54]:
b.sum()

21.0

In [55]:
b.sum(axis=0)

array([ 9., 12.])

In [56]:
b.sum(axis=1)

array([ 3.,  7., 11.])

In [58]:
np.sqrt(a)

array([2.23606798, 2.44948974, 3.        ])

In [60]:
np.std(b)

1.707825127659933

#### Basic mathematical operations

In [63]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
a

array([[1, 2],
       [3, 4]])

In [64]:
b

array([[5, 6],
       [7, 8]])

In [65]:
a+b

array([[ 6,  8],
       [10, 12]])

In [68]:
a*b

array([[ 5, 12],
       [21, 32]])

In [69]:
# Matrix Product
a.dot(b)

array([[19, 22],
       [43, 50]])

In [71]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])